name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: ["zjoasan", "bud3699", "itsmikethetech"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: OS
    attributes:
      label: Which OS?
      description: What version of Windows are you running?
      options:
        - Win11 Pro
        - Win11 Home
        - Win10 Pro
        - Win10 Home
        - Other..
      default: 0
    validations:
      required: true
  - type: dropdown
    id: Version
    attributes:
      label: Which release?
      description: What version of Windows are you running?
      options:
        - 24H2
        - 23H2
        - 22H2
        - 21H2
        - 1809
        - 1607
        - 1507
        - Other..
      default: 0
    validations:
      required: true
  - type: textarea
    id: bug-info
    attributes:
      label: Describe the bug
      description: Free text description.
      placeholder: Tell us what you see!
      value: "A clear and concise description of what the bug."
    validations:
      required: true 
  - type: textarea
    id: reproduce-info
    attributes:
      label: Steps to reproduce
      description: And if you can how to reproduce 
      placeholder: Tell us how to reproduce!
      value: "1. Go to '...', 2. Click on '....', and so on."
    validations:
      required: false 
  - type: textarea
    id: expected-info
    attributes:
      label: Expected behavior
      description: Please inform us about expected behavior.
      placeholder: Description of behavior!
      value: "When i Clicked..."
    validations:
      required: false 
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

