name: Feature Request
description: Request a new Feature.
title: "[Feature]: "
labels: ["remove", "customize", "companion", "enhancement", "newcode"]
assignees: ["zjoasan", "bud3699", "itsmikethetech"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request report!
  - type: textarea
    id: frprob
    attributes:
      label: Is the feature related to a "problem"?
      description: Describe the problem, in detail.
      placeholder: Tell us how to reproduce
      value: "When start X I wish to.."
    validations:
      required: true
  - type: textarea
    id: your-solution
    attributes:
      label: Your suggestion
      description: Describe what would solve your problem, as detailed as possible.
      placeholder: Tell us how to progress!
      value: "Disable a specific VD via hotkey"
    validations:
      required: true 
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

